#!/usr/bin/bash

website_dir=_website
source_dir=_posts
master=0

while getopts ":m" opt; do
  case "$opt" in
  m)
    master=1
    ;;
  ?)
    echo "ERROR: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

cleanup() {
  unset filepath_img
}

createHeader() {
  local category=$1
  # shellcheck disable=SC2129
  echo "---" >>"$index_path"
  echo "title: Index" >>"$index_path"
  echo "category: $category" >>"$index_path"
  echo "---" >>"$index_path"
}

main() {
  local file=$1

  filepath=$(basename "$file" .md)

  if [ "$master" -eq 1 ]; then
    [ -f "$website_dir/media/$filepath.avif" ] && filepath_img="media/$filepath.avif"
  else
    [ -f "$website_dir/media/$filepath.avif" ] && filepath_img="../media/$filepath.avif"
  fi

  if [ "$master" -eq 1 ]; then
    filepath="$(basename "$(dirname "$file")")/$filepath.html"
  else
    filepath="$filepath.html"
  fi

  filetitle=$(head -n 20 "$file" | grep "title:" | awk -F "title: " '{print $2}')
  filedesc=$(head -n 20 "$file" | grep "description:" | awk -F "description: " '{print $2}')
  posted=$(head -n 20 "$file" | grep "date:" | awk -F "date: " '{print $2}')
  category=$(head -n 20 "$file" | grep "category:" | awk -F "category: " '{print $2}')

  generateIndex "$sub_dir"
}

generateIndex() {
  local sub_dir index_path
  sub_dir=$1
  if [ -n "$1" ]; then
    index_path="$sub_dir/index.md"
  else
    index_path="index.md"
  fi

  [ ! -f "$index_path" ] && {
    case "$master" in
    1)
      createHeader "Master"
      ;;
    0)
      createHeader "$category"
      ;;
    esac
  }

  # shellcheck disable=SC2129
  echo "## [$filetitle]($filepath)" >>"$index_path"
  echo "" >>"$index_path"
  echo "Posted on **$posted** • **$category**" >>"$index_path"
  echo "" >>"$index_path"
  echo "> $filedesc" >>"$index_path"
  echo "" >>"$index_path"
  [ -n "$filepath_img" ] && echo "![]($filepath_img)" >>"$index_path"
  echo "" >>"$index_path"
}

while getopts ":d:" opt; do
  case "$opt" in
  d)
    subdirs=("$@")
    ;;
  ?)
    echo "ERROR: Invalid option '-$OPTARG'" >&2
    exit 1
    ;;
  esac
done

shift $((OPTIND - 1))

# shellcheck disable=2128
case "$master" in
0)
  [ -z "$subdirs" ] && mapfile -t subdirs < <(find "$source_dir" -maxdepth 1 -type d)

  for sub_dir in "${subdirs[@]}"; do
    case "$sub_dir" in
    _posts/media)
      continue
      ;;
    _posts)
      continue
      ;;
    _posts/_posts)
      continue
      ;;
    esac

    source_files=$(find "$sub_dir" -maxdepth 1 -type f -name "????-??-??-*" | sort -r)

    [ -f "$sub_dir-index.md" ] && rm "$sub_dir-index.md"

    for file in $source_files; do
      main "$file"
      cleanup
    done

    sub_dir=$(basename "$sub_dir")
    bash build-pages "$source_dir/$sub_dir/index.md"
    rm "$source_dir/$sub_dir/index.md"
  done
  ;;
1)
  # Generate master Index
  source_files=$(find "$source_dir" -type f -name "????-??-??-*.md" | sort -t/ -k3r)

  for file in $source_files; do
    main "$file"
    cleanup
  done

  bash build-pages index.md
  rm index.md
  echo "Master Index built"
  ;;
esac

echo "Indexes built."
