allow-external-apps = true
volume-keys = volume
fullscreen = true
extra-keys = []
use-black-ui = true
shortcut.create-session = ctrl + 1
shortcut.next-session = ctrl + 2
shortcut.previous-session = ctrl + 3
shortcut.rename-session = ctrl + 4
