# Ranger Variables
# %f - Current hover file
# %d - Current directory
# %s - Current selected files

set colorscheme elegantvagrant
set preview_images_method ueberzug
set preview_images true
set preview_script ~/.config/ranger/scope.sh
set show_hidden false

map e shell nvim %f                       # Open file with neovim
map q quit                                # Quit ranger
map <C-Space> shell swayimg --gallery %f  # Open swayimg thumbnail mode on selected directory
map i shell ./%f                          # Run scripts
map cq shell cmus-remote --queue %s       # Add selected files to cmus queue

# Zoxide
# git clone git@github.com:jchook/ranger-zoxide.git ~/.config/ranger/plugins/zoxide
map l move_right_and_zadd
map h move_left_and_zadd
