backend = "xrender";
rules = (
  { opacity = 1.00; },
  { inactive-opacity-override = true; },
  { match = "class_g ?= 'Kitty'"; opacity = 0.95; },
  { match = "class_g ?= 'Neovide'"; opacity = 0.95; },
  { match = "class_g ?= 'com.mitchellh.ghostty'"; opacity = 0.95; },
  { match = "class_g ?= 'Alacritty'"; opacity = 0.95; },
  { match = "class_g ?= 'st-256color'"; opacity = 0.95; },
  { match = "class_g ?= 'emacs'"; opacity = 0.95; }
)
